#!/bin/bash

(make clean; make)

total=0
totalmax=0

rm -f total.txt *out total.txt

# Test driver
function runtest {
  prog=$1
  args=$2
  testinput=$3
  grade=$4
  totalmax=`expr $totalmax + $grade`;

  inputdescr=
  if [ "$testinput" != "none" ]; then
      inputdescr=" < $testinput"
  fi
  descr="$prog $args $inputdescr"
  
  echo "======= $descr ==========="
  ./$prog $args < $testinput > $prog.out
  ./$prog.org $args< $testinput > $prog.org.out
  diff $prog.out $prog.org.out > diff.out
  if [ $? -eq 0 ]; then
      cat $prog.out
      echo Test passed...;
      printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
      total=`expr $total + $grade`;
  else
      echo "*****Test Failed*****";
      echo ------ Your Output ----------
      cat $prog.out
      echo ------ Expected Output ------
      cat $prog.org.out
      echo ------ Difference -----------
      cat diff.out
      echo -----------------------------
      printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
  fi
  echo
}

# Test driver2 to test the wav output
function runtest2 {
  prog=$1
  args=$2
  testinput=$3
  grade=$4
  inputdescr=
  if [ "$testinput" != "none" ]; then
      inputdescr=" < $testinput"
  fi
  descr="./$prog $args $inputdescr && diff $args.wav org-$args.wav"
  
  totalmax=`expr $totalmax + $grade`;

  echo "======= $descr ==========="
  rm -f $args.wav
  ./$prog $args.freq < $testinput > $prog.out
  diff $args.wav org-$args.wav > diff.out
  if [ $? -eq 0 ]; then
#      cat $prog.out
      echo Test passed...;
      echo files $args and org-$args are the same
      printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
      total=`expr $total + $grade`;
  else
      echo "*****Test Failed*****";
      echo files $args and org-$args are different
      printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
  fi
  echo
}

rm songs/*.wav

# List of tests running
runtest test_mysort "test1" none 4
runtest test_mysort "test2" none 4
runtest test_mysort "test3" none 4
runtest test_mysort "test4" none 4
runtest test_mysort "test5" none 4
runtest freq2wav "xx" none 3
runtest freq2wav "songs/notexisting.freq" none 3
runtest freq2wav "songs/bolero.freq" none 3
runtest freq2wav "songs/birthday.freq" none 3
runtest freq2wav "songs/popcorn.freq" none 3
runtest freq2wav "songs/bumblebee.freq" none 3
runtest2 freq2wav "songs/bolero" none 4
runtest2 freq2wav "songs/birthday" none 4
runtest2 freq2wav "songs/popcorn" none 3
runtest2 freq2wav "songs/bumblebee" none 3
runtest test_bits "test1" none 4
runtest test_bits "test2" none 4
runtest test_bits "test3" none 4
runtest test_bits "test4" none 4
runtest test_bits "test5" none 4
runtest life "" none 3
runtest life "300" none 3
runtest life "30" none 4
runtest life "54" none 3
runtest life "126" none 3
runtest life "182" none 3
runtest life "94" none 3
runtest life "182" none 3
runtest life "222" none 3

echo > total.out
echo >> total.out
echo   "-------------------------------------------------" >> total.out
echo   "CS240: Lab 6. $USER   " >> total.out
date >> total.out
echo   "-------------------------------------------------" >> total.out
cat total.txt >> total.out >> total.out
echo   "-------------------------------------------------" >> total.out
echo   "CS240: Lab 6. $USER" `date` " Total: " $total of $totalmax >> total.out
echo >> total.out

cat total.out
cat total.out >> .local.total.out

#Do not remove or comment these lines. They are used for monitoring progress.
labout=/homes/cs240/LABOUT/lab6/$USER/total.txt
cat total.out >> $labout
git add -A  >> .local.git.out
git commit -a -m "$total of $totalmax" >> .local.git.out


